CREATE TABLE `tbl_currency` (
	`tbl_currency_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`tbl_currency_code`	TEXT NOT NULL,
	`tbl_currency_name`	TEXT NOT NULL,
	`tbl_currency_country_id`	INTEGER NOT NULL
)

INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AFN', 'Afghanistan Afghani', 1);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ALL', 'Albanian Lek', 2);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('DZD', 'Algerian Dinar', 3);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 4);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 5);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AOA', 'Angolan Kwanza', 6);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Caribbean Dollar', 7);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Caribbean Dollar', 8);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Caribbean Dollar', 9);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ARS', 'Argentine Peso', 10);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AMD', 'Armenian Dram', 11);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AWG', 'Aruban Guilder', 12);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AUD', 'Australian Dollar', 13);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 14);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AZN', 'Azerbaijan New Manat', 15);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BSD', 'Bahamian Dollar', 16);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BHD', 'Bahraini Dinar', 17);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BDT', 'Bangladeshi Taka', 18);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BBD', 'Barbados Dollar', 19);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BYR', 'Belarussian Ruble', 20);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 21);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BZD', 'Belize Dollar', 22);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XOF', 'CFA Franc BCEAO', 23);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BMD', 'Bermudian Dollar', 24);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BTN', 'Bhutan Ngultrum', 25);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BOB', 'Boliviano', 26);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BAM', 'Marka', 27);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BWP', 'Botswana Pula', 28);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NOK', 'Norwegian Krone', 29);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BRL', 'Brazilian Real', 30);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 31);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BND', 'Brunei Dollar', 32);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BGN', 'Bulgarian Lev', 33);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XOF', 'CFA Franc BCEAO', 34);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('BIF', 'Burundi Franc', 35);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KHR', 'Kampuchean Riel', 36);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XAF', 'CFA Franc BEAC', 37);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CAD', 'Canadian Dollar', 38);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CVE', 'Cape Verde Escudo', 39);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KYD', 'Cayman Islands Dollar', 40);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XAF', 'CFA Franc BEAC', 41);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XAF', 'CFA Franc BEAC', 42);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CLP', 'Chilean Peso', 43);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CNY', 'Yuan Renminbi', 44);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AUD', 'Australian Dollar', 45);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AUD', 'Australian Dollar', 46);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('COP', 'Colombian Peso', 47);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KMF', 'Comoros Franc', 48);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XAF', 'CFA Franc BEAC', 49);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CDF', 'Francs', 50);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NZD', 'New Zealand Dollar', 51);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CRC', 'Costa Rican Colon', 52);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('HRK', 'Croatian Kuna', 53);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CUP', 'Cuban Peso', 54);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 55);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CZK', 'Czech Koruna', 56);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('DKK', 'Danish Krone', 57);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('DJF', 'Djibouti Franc', 58);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Caribbean Dollar', 59);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('DOP', 'Dominican Peso', 60);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ECS', 'Ecuador Sucre', 61);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EGP', 'Egyptian Pound', 62);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SVC', 'El Salvador Colon', 63);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XAF', 'CFA Franc BEAC', 64);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ERN', 'Eritrean Nakfa', 65);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 66);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ETB', 'Ethiopian Birr', 67);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 68);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('FKP', 'Falkland Islands Pound', 69);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('DKK', 'Danish Krone', 70);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('FJD', 'Fiji Dollar', 71);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 72);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 73);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 74);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 75);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XAF', 'CFA Franc BEAC', 76);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GMD', 'Gambian Dalasi', 77);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GEL', 'Georgian Lari', 78);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 79);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GHS', 'Ghanaian Cedi', 80);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GIP', 'Gibraltar Pound', 81);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GBP', 'Pound Sterling', 82);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 83);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('DKK', 'Danish Krone', 84);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Carribean Dollar', 85);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 86);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 87);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('QTQ', 'Guatemalan Quetzal', 88);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GGP', 'Pound Sterling', 89);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GNF', 'Guinea Franc', 90);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GWP', 'Guinea-Bissau Peso', 91);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GYD', 'Guyana Dollar', 92);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('HTG', 'Haitian Gourde', 93);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AUD', 'Australian Dollar', 94);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('HNL', 'Honduran Lempira', 95);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('HKD', 'Hong Kong Dollar', 96);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('HUF', 'Hungarian Forint', 97);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ISK', 'Iceland Krona', 98);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('INR', 'Indian Rupee', 99);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('IDR', 'Indonesian Rupiah', 100);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('IRR', 'Iranian Rial', 101);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('IQD', 'Iraqi Dinar', 102);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 103);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GBP', 'Pound Sterling', 104);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ILS', 'Israeli New Shekel', 105);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 106);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XOF', 'CFA Franc BCEAO', 107);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('JMD', 'Jamaican Dollar', 108);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('JPY', 'Japanese Yen', 109);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GBP', 'Pound Sterling', 110);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('JOD', 'Jordanian Dinar', 111);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KZT', 'Kazakhstan Tenge', 112);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KES', 'Kenyan Shilling', 113);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AUD', 'Australian Dollar', 114);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KPW', 'North Korean Won', 115);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KRW', 'Korean Won', 116);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KWD', 'Kuwaiti Dinar', 117);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('KGS', 'Som', 118);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('LAK', 'Lao Kip', 119);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('LVL', 'Latvian Lats', 120);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('LBP', 'Lebanese Pound', 121);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('LSL', 'Lesotho Loti', 122);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('LRD', 'Liberian Dollar', 123);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('LYD', 'Libyan Dinar', 124);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CHF', 'Swiss Franc', 125);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('LTL', 'Lithuanian Litas', 126);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 127);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MOP', 'Macau Pataca', 128);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MKD', 'Denar', 129);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MGF', 'Malagasy Franc', 130);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MWK', 'Malawi Kwacha', 131);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MYR', 'Malaysian Ringgit', 132);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MVR', 'Maldive Rufiyaa', 133);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XOF', 'CFA Franc BCEAO', 134);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 135);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 136);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 137);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MRO', 'Mauritanian Ouguiya', 138);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MUR', 'Mauritius Rupee', 139);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 140);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MXN', 'Mexican Nuevo Peso', 141);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 142);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MDL', 'Moldovan Leu', 143);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 144);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MNT', 'Mongolian Tugrik', 145);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 146);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Caribbean Dollar', 147);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MAD', 'Moroccan Dirham', 148);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MZN', 'Mozambique Metical', 149);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MMK', 'Myanmar Kyat', 150);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NAD', 'Namibian Dollar', 151);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AUD', 'Australian Dollar', 152);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NPR', 'Nepalese Rupee', 153);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 154);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ANG', 'Netherlands Antillean Guilder', 155);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XPF', 'CFP Franc', 156);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NZD', 'New Zealand Dollar', 157);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NIO', 'Nicaraguan Cordoba Oro', 158);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XOF', 'CFA Franc BCEAO', 159);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NGN', 'Nigerian Naira', 160);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NZD', 'New Zealand Dollar', 161);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AUD', 'Australian Dollar', 162);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 163);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NOK', 'Norwegian Krone', 164);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('OMR', 'Omani Rial', 165);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('PKR', 'Pakistan Rupee', 166);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 167);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('PAB', 'Panamanian Balboa', 168);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('PGK', 'Papua New Guinea Kina', 169);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('PYG', 'Paraguay Guarani', 170);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('PEN', 'Peruvian Nuevo Sol', 171);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('PHP', 'Philippine Peso', 172);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NZD', 'New Zealand Dollar', 173);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('PLN', 'Polish Zloty', 174);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XPF', 'CFP Franc', 175);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 176);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 177);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('QAR', 'Qatari Rial', 178);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 179);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('RON', 'Romanian New Leu', 180);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('RUB', 'Russian Ruble', 181);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('RWF', 'Rwanda Franc', 182);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SHP', 'St. Helena Pound', 183);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Caribbean Dollar', 184);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Caribbean Dollar', 185);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 186);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XCD', 'East Caribbean Dollar', 187);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('WST', 'Samoan Tala', 188);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 189);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('STD', 'Dobra', 190);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SAR', 'Saudi Riyal', 191);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XOF', 'CFA Franc BCEAO', 192);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('RSD', 'Dinar', 193);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SCR', 'Seychelles Rupee', 194);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SLL', 'Sierra Leone Leone', 195);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SGD', 'Singapore Dollar', 196);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 197);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 198);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SBD', 'Solomon Islands Dollar', 199);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SOS', 'Somali Shilling', 200);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ZAR', 'South African Rand', 201);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GBP', 'Pound Sterling', 202);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SSP', 'South Sudan Pound', 203);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 204);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('LKR', 'Sri Lanka Rupee', 205);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SDG', 'Sudanese Pound', 206);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SRD', 'Surinam Dollar', 207);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NOK', 'Norwegian Krone', 208);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SZL', 'Swaziland Lilangeni', 209);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SEK', 'Swedish Krona', 210);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('CHF', 'Swiss Franc', 211);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('SYP', 'Syrian Pound', 212);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('TWD', 'Taiwan Dollar', 213);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('TJS', 'Tajik Somoni', 214);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('TZS', 'Tanzanian Shilling', 215);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('THB', 'Thai Baht', 216);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XOF', 'CFA Franc BCEAO', 217);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('NZD', 'New Zealand Dollar', 218);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('TOP', 'Tongan Paanga', 219);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('TTD', 'Trinidad and Tobago Dollar', 220);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('TND', 'Tunisian Dollar', 221);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('TRY', 'Turkish Lira', 222);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('TMT', 'Manat', 223);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 224);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AUD', 'Australian Dollar', 225);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('GBP', 'Pound Sterling', 226);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('UGX', 'Uganda Shilling', 227);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('UAH', 'Ukraine Hryvnia', 228);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('AED', 'Arab Emirates Dirham', 229);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('UYU', 'Uruguayan Peso', 230);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 231);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 232);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('UZS', 'Uzbekistan Sum', 233);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('VUV', 'Vanuatu Vatu', 234);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('EUR', 'Euro', 235);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('VEF', 'Venezuelan Bolivar', 236);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('VND', 'Vietnamese Dong', 237);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 238);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('USD', 'US Dollar', 239);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('XPF', 'CFP Franc', 240);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('MAD', 'Moroccan Dirham', 241);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('YER', 'Yemeni Rial', 242);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ZMW', 'Zambian Kwacha', 243);
INSERT INTO tbl_currency (tbl_currency_code, tbl_currency_name, tbl_currency_country_id) VALUES('ZWD', 'Zimbabwe Dollar', 244);


-- DELETE FROM tbl_currency;
-- UPDATE SQLITE_SEQUENCE SET SEQ=0 WHERE NAME='tbl_currency';
-- select * from tbl_currency;
-- end transaction;
-- VACUUM;

DROP TABLE IF EXISTS tbl_currency;
