CREATE TABLE `tbl_country` (
	`tbl_country_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`tbl_country_iso_code`	TEXT NOT NULL,
	`tbl_country_name`	TEXT NOT NULL,
	`tbl_country_capital`	TEXT
)

INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('af', 'Afghanistan', 'Kabul');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('al', 'Albania', 'Tirana');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('dz', 'Algeria', 'Algiers');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('as', 'American Samoa', 'Pago Pago');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ad', 'Andorra', 'Andorra');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ao', 'Angola', 'Luanda');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ai', 'Anguilla', 'The Valley');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('aq', 'Antarctica', 'None');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ag', 'Antigua and Barbuda', 'St. Johns');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ar', 'Argentina', 'Buenos Aires');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('am', 'Armenia', 'Yerevan');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('aw', 'Aruba', 'Oranjestad');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('au', 'Australia', 'Canberra');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('at', 'Austria', 'Vienna');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('az', 'Azerbaijan', 'Baku');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bs', 'Bahamas', 'Nassau');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bh', 'Bahrain', 'Al-Manamah');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bd', 'Bangladesh', 'Dhaka');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bb', 'Barbados', 'Bridgetown');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('by', 'Belarus', 'Minsk');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('be', 'Belgium', 'Brussels');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bz', 'Belize', 'Belmopan');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bj', 'Benin', 'Porto-Novo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bm', 'Bermuda', 'Hamilton');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bt', 'Bhutan', 'Thimphu');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bo', 'Bolivia', 'La Paz');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ba', 'Bosnia-Herzegovina', 'Sarajevo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bw', 'Botswana', 'Gaborone');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bv', 'Bouvet Island', 'None');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('br', 'Brazil', 'Brasilia');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('io', 'British Indian Ocean Territory', 'None');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bn', 'Brunei Darussalam', 'Bandar Seri Begawan');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bg', 'Bulgaria', 'Sofia');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bf', 'Burkina Faso', 'Ouagadougou');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('bi', 'Burundi', 'Bujumbura');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('kh', 'Cambodia', 'Phnom Penh');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cm', 'Cameroon', 'Yaounde');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ca', 'Canada', 'Ottawa');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cv', 'Cape Verde', 'Praia');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ky', 'Cayman Islands', 'Georgetown');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cf', 'Central African Republic', 'Bangui');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('td', 'Chad', 'NDjamena');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cl', 'Chile', 'Santiago');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cn', 'China', 'Beijing');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cx', 'Christmas Island', 'The Settlement');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cc', 'Cocos (Keeling) Islands', 'West Island');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('co', 'Colombia', 'Bogota');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('km', 'Comoros', 'Moroni');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cg', 'Congo', 'Brazzaville');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cd', 'Congo, Dem. Republic', 'Kinshasa');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ck', 'Cook Islands', 'Avarua');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cr', 'Costa Rica', 'San Jose');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('hr', 'Croatia', 'Zagreb');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cu', 'Cuba', 'Havana');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cy', 'Cyprus', 'Nicosia');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('cz', 'Czech Rep.', 'Prague');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('dk', 'Denmark', 'Copenhagen');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('dj', 'Djibouti', 'Djibouti');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('dm', 'Dominica', 'Roseau');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('do', 'Dominican Republic', 'Santo Domingo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ec', 'Ecuador', 'Quito');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('eg', 'Egypt', 'Cairo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sv', 'El Salvador', 'San Salvador');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gq', 'Equatorial Guinea', 'Malabo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('er', 'Eritrea', 'Asmara');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ee', 'Estonia', 'Tallinn');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('et', 'Ethiopia', 'Addis Ababa');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('eu.int', 'European Union', 'Brussels');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('fk', 'Falkland Islands (Malvinas)', 'Stanley');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('fo', 'Faroe Islands', 'Torshavn');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('fj', 'Fiji', 'Suva');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('fi', 'Finland', 'Helsinki');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('fr', 'France', 'Paris');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gf', 'French Guiana', 'Cayenne');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tf', 'French Southern Territories', 'None');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ga', 'Gabon', 'Libreville');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gm', 'Gambia', 'Banjul');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ge', 'Georgia', 'Tbilisi');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('de', 'Germany', 'Berlin');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gh', 'Ghana', 'Accra');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gi', 'Gibraltar', 'Gibraltar');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gb', 'Great Britain', 'London');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gr', 'Greece', 'Athens');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gl', 'Greenland', 'Godthab');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gd', 'Grenada', 'St. Georges');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gp', 'Guadeloupe (French)', 'Basse-Terre');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gu', 'Guam (USA)', 'Agana');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gt', 'Guatemala', 'Guatemala City');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gg', 'Guernsey', 'St. Peter Port');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gn', 'Guinea', 'Conakry');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gw', 'Guinea Bissau', 'Bissau');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gy', 'Guyana', 'Georgetown');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ht', 'Haiti', 'Port-au-Prince');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('hm', 'Heard Island and McDonald Islands', 'None');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('hn', 'Honduras', 'Tegucigalpa');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('hk', 'Hong Kong', 'Victoria');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('hu', 'Hungary', 'Budapest');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('is', 'Iceland', 'Reykjavik');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('in', 'India', 'New Delhi');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('id', 'Indonesia', 'Jakarta');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ir', 'Iran', 'Tehran');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('iq', 'Iraq', 'Baghdad');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ie', 'Ireland', 'Dublin');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('im', 'Isle of Man', 'Douglas');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('il', 'Israel', 'Jerusalem');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('it', 'Italy', 'Rome');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ci', 'Ivory Coast', 'Abidjan');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('jm', 'Jamaica', 'Kingston');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('jp', 'Japan', 'Tokyo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('je', 'Jersey', 'Saint Helier');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('jo', 'Jordan', 'Amman');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('kz', 'Kazakhstan', 'Astana');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ke', 'Kenya', 'Nairobi');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ki', 'Kiribati', 'Tarawa');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('kp', 'Korea-North', 'Pyongyang');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('kr', 'Korea-South', 'Seoul');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('kw', 'Kuwait', 'Kuwait City');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('kg', 'Kyrgyzstan', 'Bishkek');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('la', 'Laos', 'Vientiane');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('lv', 'Latvia', 'Riga');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('lb', 'Lebanon', 'Beirut');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ls', 'Lesotho', 'Maseru');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('lr', 'Liberia', 'Monrovia');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ly', 'Libya', 'Tripoli');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('li', 'Liechtenstein', 'Vaduz');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('lt', 'Lithuania', 'Vilnius');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('lu', 'Luxembourg', 'Luxembourg');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mo', 'Macau', 'Macau');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mk', 'Macedonia', 'Skopje');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mg', 'Madagascar', 'Antananarivo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mw', 'Malawi', 'Lilongwe');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('my', 'Malaysia', 'Kuala Lumpur');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mv', 'Maldives', 'Male');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ml', 'Mali', 'Bamako');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mt', 'Malta', 'Valletta');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mh', 'Marshall Islands', 'Majuro');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mq', 'Martinique (French)', 'Fort-de-France');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mr', 'Mauritania', 'Nouakchott');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mu', 'Mauritius', 'Port Louis');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('yt', 'Mayotte', 'Dzaoudzi');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mx', 'Mexico', 'Mexico City');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('fm', 'Micronesia', 'Palikir');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('md', 'Moldova', 'Kishinev');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mc', 'Monaco', 'Monaco');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mn', 'Mongolia', 'Ulan Bator');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('me', 'Montenegro', 'Podgorica');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ms', 'Montserrat', 'Plymouth');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ma', 'Morocco', 'Rabat');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mz', 'Mozambique', 'Maputo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mm', 'Myanmar', 'Naypyidaw');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('na', 'Namibia', 'Windhoek');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('nr', 'Nauru', 'Yaren');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('np', 'Nepal', 'Kathmandu');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('nl', 'Netherlands', 'Amsterdam');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('an', 'Netherlands Antilles', 'Willemstad');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('nc', 'New Caledonia (French)', 'Noumea');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('nz', 'New Zealand', 'Wellington');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ni', 'Nicaragua', 'Managua');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ne', 'Niger', 'Niamey');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ng', 'Nigeria', 'Lagos');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('nu', 'Niue', 'Alofi');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('nf', 'Norfolk Island', 'Kingston');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('mp', 'Northern Mariana Islands', 'Saipan');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('no', 'Norway', 'Oslo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('om', 'Oman', 'Muscat');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pk', 'Pakistan', 'Islamabad');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pw', 'Palau', 'Koror');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pa', 'Panama', 'Panama City');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pg', 'Papua New Guinea', 'Port Moresby');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('py', 'Paraguay', 'Asuncion');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pe', 'Peru', 'Lima');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ph', 'Philippines', 'Manila');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pn', 'Pitcairn Island', 'Adamstown');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pl', 'Poland', 'Warsaw');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pf', 'Polynesia (French)', 'Papeete');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pt', 'Portugal', 'Lisbon');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pr', 'Puerto Rico', 'San Juan');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('qa', 'Qatar', 'Doha');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('re', 'Reunion (French)', 'Saint-Denis');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ro', 'Romania', 'Bucharest');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ru', 'Russia', 'Moscow');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('rw', 'Rwanda', 'Kigali');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sh', 'Saint Helena', 'Jamestown');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('kn', 'Saint Kitts & Nevis Anguilla', 'Basseterre');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('lc', 'Saint Lucia', 'Castries');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('pm', 'Saint Pierre and Miquelon', 'St. Pierre');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('vc', 'Saint Vincent & Grenadines', 'Kingstown');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ws', 'Samoa', 'Apia');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sm', 'San Marino', 'San Marino');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('st', 'Sao Tome and Principe', 'Sao Tome');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sa', 'Saudi Arabia', 'Riyadh');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sn', 'Senegal', 'Dakar');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('rs', 'Serbia', 'Belgrade');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sc', 'Seychelles', 'Victoria');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sl', 'Sierra Leone', 'Freetown');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sg', 'Singapore', 'Singapore');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sk', 'Slovakia', 'Bratislava');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('si', 'Slovenia', 'Ljubljana');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sb', 'Solomon Islands', 'Honiara');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('so', 'Somalia', 'Mogadishu');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('za', 'South Africa', 'Pretoria');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('gs', 'South Georgia & South Sandwich Islands', 'None');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ss', 'South Sudan', 'Ramciel');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('es', 'Spain', 'Madrid');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('lk', 'Sri Lanka', 'Colombo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sd', 'Sudan', 'Khartoum');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sr', 'Suriname', 'Paramaribo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sj', 'Svalbard and Jan Mayen Islands', 'Longyearbyen');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sz', 'Swaziland', 'Mbabane');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('se', 'Sweden', 'Stockholm');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ch', 'Switzerland', 'Bern');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('sy', 'Syria', 'Damascus');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tw', 'Taiwan', 'Taipei');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tj', 'Tajikistan', 'Dushanbe');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tz', 'Tanzania', 'Dodoma');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('th', 'Thailand', 'Bangkok');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tg', 'Togo', 'Lome');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tk', 'Tokelau', 'None');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('to', 'Tonga', 'Nukualofa');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tt', 'Trinidad and Tobago', 'Port of Spain');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tn', 'Tunisia', 'Tunis');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tr', 'Turkey', 'Ankara');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tm', 'Turkmenistan', 'Ashgabat');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tc', 'Turks and Caicos Islands', 'Grand Turk');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('tv', 'Tuvalu', 'Funafuti');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('uk', 'U.K.', 'London');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ug', 'Uganda', 'Kampala');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ua', 'Ukraine', 'Kiev');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ae', 'United Arab Emirates', 'Abu Dhabi');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('uy', 'Uruguay', 'Montevideo');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('us', 'USA', 'Washington');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('um', 'USA Minor Outlying Islands', 'None');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('uz', 'Uzbekistan', 'Tashkent');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('vu', 'Vanuatu', 'Port Vila');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('va', 'Vatican', 'Vatican City');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ve', 'Venezuela', 'Caracas');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('vn', 'Vietnam', 'Hanoi');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('vg', 'Virgin Islands (British)', 'Road Town');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('vi', 'Virgin Islands (USA)', 'Charlotte Amalie');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('wf', 'Wallis and Futuna Islands', 'Mata-Utu');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('eh', 'Western Sahara', 'El Aaiun');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('ye', 'Yemen', 'Sana');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('zm', 'Zambia', 'Lusaka');
INSERT INTO tbl_country (tbl_country_iso_code, tbl_country_name, tbl_country_capital) VALUES('zw', 'Zimbabwe', 'Harare');

-- select * from tbl_country;


DROP TABLE IF EXISTS tbl_country;

